# Generated by Django 5.2.5 on 2025-08-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='t_condominios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_activo', models.BooleanField(default=True)),
                ('f_creado_en', models.DateTimeField(auto_now_add=True)),
                ('f_actualizado_en', models.DateTimeField(auto_now_add=True)),
                ('f_nombre', models.CharField(max_length=200)),
                ('f_direccion', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 't_condominios',
            },
        ),
    ]
