# Generated by Django 5.2.5 on 2025-09-06 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_condominios',
            name='f_actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='t_condominios',
            name='f_direccion',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.CreateModel(
            name='t_edificios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_activo', models.BooleanField(default=True)),
                ('f_creado_en', models.DateTimeField(auto_now_add=True)),
                ('f_actualizado_en', models.DateTimeField(auto_now=True)),
                ('f_nombre', models.CharField(max_length=120)),
                ('f_condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edificios', to='catalogo.t_condominios')),
            ],
            options={
                'db_table': 't_edificios',
            },
        ),
        migrations.CreateModel(
            name='t_apartamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_activo', models.BooleanField(default=True)),
                ('f_creado_en', models.DateTimeField(auto_now_add=True)),
                ('f_actualizado_en', models.DateTimeField(auto_now=True)),
                ('f_numero', models.CharField(max_length=20)),
                ('f_nivel', models.CharField(blank=True, default='', max_length=10)),
                ('f_edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartamentos', to='catalogo.t_edificios')),
            ],
            options={
                'verbose_name': 'Apartamento',
                'verbose_name_plural': 'Apartamentos',
                'db_table': 't_apartamentos',
            },
        ),
        migrations.AddConstraint(
            model_name='t_edificios',
            constraint=models.UniqueConstraint(fields=('f_condominio', 'f_nombre'), name='uq_edificio_por_condominio'),
        ),
        migrations.AddConstraint(
            model_name='t_apartamentos',
            constraint=models.UniqueConstraint(fields=('f_edificio', 'f_numero'), name='unico_apartamento_por_edificio'),
        ),
    ]
