# Generated by Django 5.2.5 on 2025-09-13 11:26

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_t_condominios_f_actualizado_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t_apartamentos',
            options={'ordering': ['f_edificio', 'f_numero'], 'verbose_name': 'Apartamento', 'verbose_name_plural': 'Apartamentos'},
        ),
        migrations.AlterModelOptions(
            name='t_condominios',
            options={'ordering': ['f_nombre', 'f_direccion'], 'verbose_name': 'Condominio', 'verbose_name_plural': 'Condominios'},
        ),
        migrations.AlterModelOptions(
            name='t_edificios',
            options={'ordering': ['f_condominio', 'f_nombre'], 'verbose_name': 'Edificio', 'verbose_name_plural': 'Edificios'},
        ),
        migrations.AddConstraint(
            model_name='t_condominios',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('f_nombre'), name='ux_condominio_nombre_ci'),
        ),
    ]
