# Generated by Django 5.2.5 on 2025-10-22 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0003_alter_t_apartamentos_options_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_invitaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_activo', models.BooleanField(default=True)),
                ('f_creado_en', models.DateTimeField(auto_now_add=True)),
                ('f_actualizado_en', models.DateTimeField(auto_now=True)),
                ('f_invitado_nombre', models.CharField(max_length=120)),
                ('f_invitado_doc', models.CharField(blank=True, default='', max_length=32)),
                ('f_inicio', models.DateTimeField()),
                ('f_fin', models.DateTimeField()),
                ('f_estado', models.CharField(choices=[('PEND', 'Pendiente'), ('USED', 'Usada'), ('CANC', 'Cancelada'), ('EXPD', 'Vencida')], db_index=True, default='PEND', max_length=4)),
                ('f_token', models.CharField(blank=True, db_index=True, default='', max_length=64, unique=True)),
                ('f_usada_en', models.DateTimeField(blank=True, null=True)),
                ('f_apartamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitaciones', to='catalogo.t_apartamentos')),
                ('f_host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitaciones', to='usuarios.t_residentes')),
            ],
            options={
                'db_table': 't_invitaciones',
                'ordering': ['-f_creado_en'],
            },
        ),
        migrations.CreateModel(
            name='t_accesos_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_activo', models.BooleanField(default=True)),
                ('f_creado_en', models.DateTimeField(auto_now_add=True)),
                ('f_actualizado_en', models.DateTimeField(auto_now=True)),
                ('f_resultado', models.CharField(choices=[('OK', 'Válido'), ('EXP', 'Expirada'), ('CAN', 'Cancelada'), ('INV', 'Inválida')], max_length=3)),
                ('f_detalle', models.CharField(blank=True, default='', max_length=200)),
                ('f_invitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='accesos.t_invitaciones')),
            ],
            options={
                'db_table': 't_accesos_log',
                'ordering': ['-f_creado_en'],
            },
        ),
        migrations.AddIndex(
            model_name='t_invitaciones',
            index=models.Index(fields=['f_apartamento', 'f_estado'], name='t_invitacio_f_apart_e92f37_idx'),
        ),
        migrations.AddIndex(
            model_name='t_invitaciones',
            index=models.Index(fields=['f_host', 'f_estado'], name='t_invitacio_f_host__916d4e_idx'),
        ),
        migrations.AddConstraint(
            model_name='t_invitaciones',
            constraint=models.CheckConstraint(condition=models.Q(('f_fin__gt', models.F('f_inicio'))), name='ck_inv_ventana_valida'),
        ),
    ]
