# Generated by Django 5.2.5 on 2025-09-13 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0003_alter_t_apartamentos_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='t_residentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_activo', models.BooleanField(default=True)),
                ('f_creado_en', models.DateTimeField(auto_now_add=True)),
                ('f_actualizado_en', models.DateTimeField(auto_now=True)),
                ('f_nombres', models.CharField(max_length=80)),
                ('f_apellidos', models.CharField(max_length=80)),
                ('f_tipo_documento', models.CharField(choices=[('CED', 'Cédula'), ('PAS', 'Pasaporte')], max_length=3)),
                ('f_num_documento', models.CharField(db_index=True, max_length=32)),
                ('f_fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('f_nacionalidad', models.CharField(blank=True, default='', max_length=60)),
                ('f_email', models.EmailField(max_length=254)),
                ('f_telefono_movil', models.CharField(max_length=20)),
                ('f_telefono_alt', models.CharField(blank=True, default='', max_length=20)),
                ('f_preferencia_contacto', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp')], default='EMAIL', max_length=9)),
                ('f_foto', models.ImageField(blank=True, null=True, upload_to='residentes/')),
                ('f_observaciones', models.TextField(blank=True, default='')),
                ('f_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='residente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Residente',
                'verbose_name_plural': 'Residentes',
                'db_table': 't_residentes',
                'ordering': ['f_nombres', 'f_apellidos'],
            },
        ),
        migrations.CreateModel(
            name='t_residentes_apartamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_activo', models.BooleanField(default=True)),
                ('f_creado_en', models.DateTimeField(auto_now_add=True)),
                ('f_actualizado_en', models.DateTimeField(auto_now=True)),
                ('f_es_principal', models.BooleanField(default=True)),
                ('f_desde', models.DateField()),
                ('f_hasta', models.DateField(blank=True, null=True)),
                ('f_rol', models.CharField(choices=[('OWNER', 'Propietario'), ('CO_OWNER', 'Copropietario'), ('TENANT', 'Inquilino'), ('FAMILY', 'Familiar'), ('GUEST', 'Huésped')], default='OWNER', max_length=10)),
                ('f_porcentaje_copropiedad', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('f_contrato_numero', models.CharField(blank=True, default='', max_length=40)),
                ('f_contrato_desde', models.DateField(blank=True, null=True)),
                ('f_contrato_hasta', models.DateField(blank=True, null=True)),
                ('f_apartamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='residentes', to='catalogo.t_apartamentos')),
                ('f_residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='usuarios.t_residentes')),
            ],
            options={
                'verbose_name': 'Vínculo Residente–Apartamento',
                'verbose_name_plural': 'Vínculos Residente–Apartamento',
                'db_table': 't_residentes_apartamentos',
                'ordering': ['f_apartamento', 'f_residente'],
            },
        ),
        migrations.AddConstraint(
            model_name='t_residentes',
            constraint=models.UniqueConstraint(fields=('f_tipo_documento', 'f_num_documento'), name='ux_residente_doc'),
        ),
        migrations.AddConstraint(
            model_name='t_residentes_apartamentos',
            constraint=models.UniqueConstraint(fields=('f_residente', 'f_apartamento'), name='uq_residente_apartamento'),
        ),
        migrations.AddConstraint(
            model_name='t_residentes_apartamentos',
            constraint=models.UniqueConstraint(condition=models.Q(('f_es_principal', True), ('f_hasta__isnull', True)), fields=('f_apartamento',), name='uq_un_principal_activo_por_apto'),
        ),
        migrations.AddConstraint(
            model_name='t_residentes_apartamentos',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('f_rol', 'TENANT'), _negated=True), models.Q(('f_contrato_desde__isnull', False), ('f_contrato_hasta__isnull', False)), _connector='OR'), name='ck_tenant_contrato'),
        ),
        migrations.AddConstraint(
            model_name='t_residentes_apartamentos',
            constraint=models.CheckConstraint(condition=models.Q(('f_porcentaje_copropiedad__isnull', True), ('f_porcentaje_copropiedad__gt', 0), _connector='OR'), name='ck_coprop_gt0_when_set'),
        ),
    ]
